// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package main

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp(in *jlexer.Lexer, out *SwapResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount_out":
			out.AmountOut = uint64(in.Uint64())
		case "pool_state":
			(out.PoolState).UnmarshalTinyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp(out *jwriter.Writer, in SwapResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount_out\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.AmountOut))
	}
	{
		const prefix string = ",\"pool_state\":"
		out.RawString(prefix)
		(in.PoolState).MarshalTinyJSON(out)
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SwapResult) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SwapResult) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp(l, v)
}
func tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp1(in *jlexer.Lexer, out *SwapParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset_in":
			out.AssetIn = string(in.String())
		case "amount_in":
			out.AmountIn = int64(in.Int64())
		case "asset_out":
			out.AssetOut = string(in.String())
		case "min_amount_out":
			if in.IsNull() {
				in.Skip()
				out.MinAmountOut = nil
			} else {
				if out.MinAmountOut == nil {
					out.MinAmountOut = new(int64)
				}
				*out.MinAmountOut = int64(in.Int64())
			}
		case "recipient":
			out.Recipient = string(in.String())
		case "beneficiary":
			if in.IsNull() {
				in.Skip()
				out.Beneficiary = nil
			} else {
				if out.Beneficiary == nil {
					out.Beneficiary = new(string)
				}
				*out.Beneficiary = string(in.String())
			}
		case "ref_bps":
			if in.IsNull() {
				in.Skip()
				out.RefBps = nil
			} else {
				if out.RefBps == nil {
					out.RefBps = new(int)
				}
				*out.RefBps = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp1(out *jwriter.Writer, in SwapParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset_in\":"
		out.RawString(prefix[1:])
		out.String(string(in.AssetIn))
	}
	{
		const prefix string = ",\"amount_in\":"
		out.RawString(prefix)
		out.Int64(int64(in.AmountIn))
	}
	{
		const prefix string = ",\"asset_out\":"
		out.RawString(prefix)
		out.String(string(in.AssetOut))
	}
	if in.MinAmountOut != nil {
		const prefix string = ",\"min_amount_out\":"
		out.RawString(prefix)
		out.Int64(int64(*in.MinAmountOut))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	if in.Beneficiary != nil {
		const prefix string = ",\"beneficiary\":"
		out.RawString(prefix)
		out.String(string(*in.Beneficiary))
	}
	if in.RefBps != nil {
		const prefix string = ",\"ref_bps\":"
		out.RawString(prefix)
		out.Int(int(*in.RefBps))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SwapParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp1(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SwapParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp1(l, v)
}
func tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp2(in *jlexer.Lexer, out *SchemaReturn) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "supported_chains":
			if in.IsNull() {
				in.Skip()
				out.SupportedChains = nil
			} else {
				in.Delim('[')
				if out.SupportedChains == nil {
					if !in.IsDelim(']') {
						out.SupportedChains = make([]string, 0, 4)
					} else {
						out.SupportedChains = []string{}
					}
				} else {
					out.SupportedChains = (out.SupportedChains)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.SupportedChains = append(out.SupportedChains, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "return_address_chains":
			if in.IsNull() {
				in.Skip()
				out.ReturnAddressChains = nil
			} else {
				in.Delim('[')
				if out.ReturnAddressChains == nil {
					if !in.IsDelim(']') {
						out.ReturnAddressChains = make([]string, 0, 4)
					} else {
						out.ReturnAddressChains = []string{}
					}
				} else {
					out.ReturnAddressChains = (out.ReturnAddressChains)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					v2 = string(in.String())
					out.ReturnAddressChains = append(out.ReturnAddressChains, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "note":
			out.Note = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp2(out *jwriter.Writer, in SchemaReturn) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"supported_chains\":"
		out.RawString(prefix[1:])
		if in.SupportedChains == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.SupportedChains {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.String(string(v4))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"return_address_chains\":"
		out.RawString(prefix)
		if in.ReturnAddressChains == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.ReturnAddressChains {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"note\":"
		out.RawString(prefix)
		out.String(string(in.Note))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SchemaReturn) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp2(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SchemaReturn) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp2(l, v)
}
func tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp3(in *jlexer.Lexer, out *ReturnRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "chain":
			out.Chain = string(in.String())
		case "address":
			out.Address = string(in.String())
		case "asset":
			out.Asset = string(in.String())
		case "amount":
			out.Amount = uint64(in.Uint64())
		case "log":
			(out.Log).UnmarshalTinyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp3(out *jwriter.Writer, in ReturnRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chain\":"
		out.RawString(prefix[1:])
		out.String(string(in.Chain))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"asset\":"
		out.RawString(prefix)
		out.String(string(in.Asset))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Amount))
	}
	{
		const prefix string = ",\"log\":"
		out.RawString(prefix)
		(in.Log).MarshalTinyJSON(out)
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v ReturnRequest) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp3(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *ReturnRequest) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp3(l, v)
}
func tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp4(in *jlexer.Lexer, out *ReturnAddress) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "chain":
			out.Chain = string(in.String())
		case "address":
			out.Address = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp4(out *jwriter.Writer, in ReturnAddress) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chain\":"
		out.RawString(prefix[1:])
		out.String(string(in.Chain))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v ReturnAddress) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp4(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *ReturnAddress) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp4(l, v)
}
func tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp5(in *jlexer.Lexer, out *RemoveLiquidityParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "lp_amount":
			out.LpAmount = uint64(in.Uint64())
		case "recipient":
			out.Recipient = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp5(out *jwriter.Writer, in RemoveLiquidityParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"lp_amount\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.LpAmount))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v RemoveLiquidityParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp5(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *RemoveLiquidityParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp5(l, v)
}
func tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp6(in *jlexer.Lexer, out *RegisterPoolParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		case "dex_contract_id":
			out.DexContractId = string(in.String())
		case "asset0_chain":
			if in.IsNull() {
				in.Skip()
				out.Asset0Chain = nil
			} else {
				if out.Asset0Chain == nil {
					out.Asset0Chain = new(string)
				}
				*out.Asset0Chain = string(in.String())
			}
		case "asset1_chain":
			if in.IsNull() {
				in.Skip()
				out.Asset1Chain = nil
			} else {
				if out.Asset1Chain == nil {
					out.Asset1Chain = new(string)
				}
				*out.Asset1Chain = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp6(out *jwriter.Writer, in RegisterPoolParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset0))
	}
	{
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	{
		const prefix string = ",\"dex_contract_id\":"
		out.RawString(prefix)
		out.String(string(in.DexContractId))
	}
	if in.Asset0Chain != nil {
		const prefix string = ",\"asset0_chain\":"
		out.RawString(prefix)
		out.String(string(*in.Asset0Chain))
	}
	if in.Asset1Chain != nil {
		const prefix string = ",\"asset1_chain\":"
		out.RawString(prefix)
		out.String(string(*in.Asset1Chain))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v RegisterPoolParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp6(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *RegisterPoolParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp6(l, v)
}
func tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp7(in *jlexer.Lexer, out *PoolInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		case "reserve0":
			out.Reserve0 = uint64(in.Uint64())
		case "reserve1":
			out.Reserve1 = uint64(in.Uint64())
		case "fee":
			out.Fee = uint64(in.Uint64())
		case "total_lp":
			out.TotalLp = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp7(out *jwriter.Writer, in PoolInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset0))
	}
	{
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	{
		const prefix string = ",\"reserve0\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Reserve0))
	}
	{
		const prefix string = ",\"reserve1\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Reserve1))
	}
	{
		const prefix string = ",\"fee\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Fee))
	}
	{
		const prefix string = ",\"total_lp\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.TotalLp))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v PoolInfo) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp7(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *PoolInfo) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp7(l, v)
}
func tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp8(in *jlexer.Lexer, out *GetPoolParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp8(out *jwriter.Writer, in GetPoolParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset0))
	}
	{
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v GetPoolParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp8(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *GetPoolParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp8(l, v)
}
func tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp9(in *jlexer.Lexer, out *FailureLog) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "reason":
			out.Reason = string(in.String())
		case "failed_at_hop":
			out.FailedAtHop = int(in.Int())
		case "original_asset":
			out.OriginalAsset = string(in.String())
		case "original_amount":
			out.OriginalAmount = uint64(in.Uint64())
		case "intermediate_asset":
			out.IntermediateAsset = string(in.String())
		case "intermediate_amount":
			out.IntermediateAmount = uint64(in.Uint64())
		case "return_address":
			if in.IsNull() {
				in.Skip()
				out.ReturnAddress = nil
			} else {
				if out.ReturnAddress == nil {
					out.ReturnAddress = new(ReturnAddress)
				}
				(*out.ReturnAddress).UnmarshalTinyJSON(in)
			}
		case "timestamp":
			out.Timestamp = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp9(out *jwriter.Writer, in FailureLog) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix[1:])
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"failed_at_hop\":"
		out.RawString(prefix)
		out.Int(int(in.FailedAtHop))
	}
	{
		const prefix string = ",\"original_asset\":"
		out.RawString(prefix)
		out.String(string(in.OriginalAsset))
	}
	{
		const prefix string = ",\"original_amount\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.OriginalAmount))
	}
	if in.IntermediateAsset != "" {
		const prefix string = ",\"intermediate_asset\":"
		out.RawString(prefix)
		out.String(string(in.IntermediateAsset))
	}
	if in.IntermediateAmount != 0 {
		const prefix string = ",\"intermediate_amount\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.IntermediateAmount))
	}
	if in.ReturnAddress != nil {
		const prefix string = ",\"return_address\":"
		out.RawString(prefix)
		(*in.ReturnAddress).MarshalTinyJSON(out)
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.String(string(in.Timestamp))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v FailureLog) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp9(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *FailureLog) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp9(l, v)
}
func tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp10(in *jlexer.Lexer, out *DexInstruction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "version":
			out.Version = string(in.String())
		case "asset_in":
			out.AssetIn = string(in.String())
		case "asset_out":
			out.AssetOut = string(in.String())
		case "recipient":
			out.Recipient = string(in.String())
		case "slippage_bps":
			if in.IsNull() {
				in.Skip()
				out.SlippageBps = nil
			} else {
				if out.SlippageBps == nil {
					out.SlippageBps = new(int)
				}
				*out.SlippageBps = int(in.Int())
			}
		case "min_amount_out":
			if in.IsNull() {
				in.Skip()
				out.MinAmountOut = nil
			} else {
				if out.MinAmountOut == nil {
					out.MinAmountOut = new(int64)
				}
				*out.MinAmountOut = int64(in.Int64())
			}
		case "beneficiary":
			if in.IsNull() {
				in.Skip()
				out.Beneficiary = nil
			} else {
				if out.Beneficiary == nil {
					out.Beneficiary = new(string)
				}
				*out.Beneficiary = string(in.String())
			}
		case "ref_bps":
			if in.IsNull() {
				in.Skip()
				out.RefBps = nil
			} else {
				if out.RefBps == nil {
					out.RefBps = new(int)
				}
				*out.RefBps = int(in.Int())
			}
		case "return_address":
			if in.IsNull() {
				in.Skip()
				out.ReturnAddress = nil
			} else {
				if out.ReturnAddress == nil {
					out.ReturnAddress = new(ReturnAddress)
				}
				(*out.ReturnAddress).UnmarshalTinyJSON(in)
			}
		case "metadata":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Metadata = make(map[string]string)
				} else {
					out.Metadata = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v7 string
					v7 = string(in.String())
					(out.Metadata)[key] = v7
					in.WantComma()
				}
				in.Delim('}')
			}
		case "amount_in":
			out.AmountIn = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp10(out *jwriter.Writer, in DexInstruction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	{
		const prefix string = ",\"asset_in\":"
		out.RawString(prefix)
		out.String(string(in.AssetIn))
	}
	{
		const prefix string = ",\"asset_out\":"
		out.RawString(prefix)
		out.String(string(in.AssetOut))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	if in.SlippageBps != nil {
		const prefix string = ",\"slippage_bps\":"
		out.RawString(prefix)
		out.Int(int(*in.SlippageBps))
	}
	if in.MinAmountOut != nil {
		const prefix string = ",\"min_amount_out\":"
		out.RawString(prefix)
		out.Int64(int64(*in.MinAmountOut))
	}
	if in.Beneficiary != nil {
		const prefix string = ",\"beneficiary\":"
		out.RawString(prefix)
		out.String(string(*in.Beneficiary))
	}
	if in.RefBps != nil {
		const prefix string = ",\"ref_bps\":"
		out.RawString(prefix)
		out.Int(int(*in.RefBps))
	}
	if in.ReturnAddress != nil {
		const prefix string = ",\"return_address\":"
		out.RawString(prefix)
		(*in.ReturnAddress).MarshalTinyJSON(out)
	}
	if len(in.Metadata) != 0 {
		const prefix string = ",\"metadata\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v8First := true
			for v8Name, v8Value := range in.Metadata {
				if v8First {
					v8First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v8Name))
				out.RawByte(':')
				out.String(string(v8Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"amount_in\":"
		out.RawString(prefix)
		out.Int64(int64(in.AmountIn))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v DexInstruction) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp10(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *DexInstruction) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp10(l, v)
}
func tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp11(in *jlexer.Lexer, out *AddLiquidityParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount0":
			out.Amount0 = uint64(in.Uint64())
		case "amount1":
			out.Amount1 = uint64(in.Uint64())
		case "recipient":
			out.Recipient = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp11(out *jwriter.Writer, in AddLiquidityParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount0\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.Amount0))
	}
	{
		const prefix string = ",\"amount1\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Amount1))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v AddLiquidityParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexRouterV2TinyjsonTmp11(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *AddLiquidityParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexRouterV2TinyjsonTmp11(l, v)
}
