// TEMPORARY AUTOGENERATED FILE: tinyjson stub code to make the package
// compilable during generation.

package  main

import (
  "github.com/CosmWasm/tinyjson/jwriter"
  "github.com/CosmWasm/tinyjson/jlexer"
)

func ( AddLiquidityParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AddLiquidityParams ) UnmarshalJSON([]byte) error { return nil }
func ( AddLiquidityParams ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* AddLiquidityParams ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_AddLiquidityParams *AddLiquidityParams

func ( DexInstruction ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DexInstruction ) UnmarshalJSON([]byte) error { return nil }
func ( DexInstruction ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* DexInstruction ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_DexInstruction *DexInstruction

func ( GetPoolParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetPoolParams ) UnmarshalJSON([]byte) error { return nil }
func ( GetPoolParams ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* GetPoolParams ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_GetPoolParams *GetPoolParams

func ( RegisterPoolParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RegisterPoolParams ) UnmarshalJSON([]byte) error { return nil }
func ( RegisterPoolParams ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* RegisterPoolParams ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_RegisterPoolParams *RegisterPoolParams

func ( RemoveLiquidityParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RemoveLiquidityParams ) UnmarshalJSON([]byte) error { return nil }
func ( RemoveLiquidityParams ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* RemoveLiquidityParams ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_RemoveLiquidityParams *RemoveLiquidityParams

func ( ReturnAddress ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ReturnAddress ) UnmarshalJSON([]byte) error { return nil }
func ( ReturnAddress ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* ReturnAddress ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_ReturnAddress *ReturnAddress

func ( SwapParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SwapParams ) UnmarshalJSON([]byte) error { return nil }
func ( SwapParams ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* SwapParams ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_SwapParams *SwapParams
