// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package routerinternal

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp(in *jlexer.Lexer, out *TokenInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "mapping_contract":
			out.MappingContract = string(in.String())
		case "chain":
			out.Chain = string(in.String())
		case "description":
			out.Description = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp(out *jwriter.Writer, in TokenInfo) {
	out.RawByte('{')
	first := true
	_ = first
	if in.MappingContract != "" {
		const prefix string = ",\"mapping_contract\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.MappingContract))
	}
	{
		const prefix string = ",\"chain\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Chain))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v TokenInfo) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *TokenInfo) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp(l, v)
}
func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp1(in *jlexer.Lexer, out *SwapResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount_out":
			out.AmountOut = string(in.String())
		case "pool_state":
			(out.PoolState).UnmarshalTinyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp1(out *jwriter.Writer, in SwapResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount_out\":"
		out.RawString(prefix[1:])
		out.String(string(in.AmountOut))
	}
	{
		const prefix string = ",\"pool_state\":"
		out.RawString(prefix)
		(in.PoolState).MarshalTinyJSON(out)
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SwapResult) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp1(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SwapResult) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp1(l, v)
}
func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp2(in *jlexer.Lexer, out *SwapParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset_in":
			out.AssetIn = string(in.String())
		case "amount_in":
			out.AmountIn = string(in.String())
		case "asset_out":
			out.AssetOut = string(in.String())
		case "min_amount_out":
			if in.IsNull() {
				in.Skip()
				out.MinAmountOut = nil
			} else {
				if out.MinAmountOut == nil {
					out.MinAmountOut = new(string)
				}
				*out.MinAmountOut = string(in.String())
			}
		case "recipient":
			out.Recipient = string(in.String())
		case "beneficiary":
			if in.IsNull() {
				in.Skip()
				out.Beneficiary = nil
			} else {
				if out.Beneficiary == nil {
					out.Beneficiary = new(string)
				}
				*out.Beneficiary = string(in.String())
			}
		case "ref_bps":
			if in.IsNull() {
				in.Skip()
				out.RefBps = nil
			} else {
				if out.RefBps == nil {
					out.RefBps = new(uint64)
				}
				*out.RefBps = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp2(out *jwriter.Writer, in SwapParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset_in\":"
		out.RawString(prefix[1:])
		out.String(string(in.AssetIn))
	}
	{
		const prefix string = ",\"amount_in\":"
		out.RawString(prefix)
		out.String(string(in.AmountIn))
	}
	{
		const prefix string = ",\"asset_out\":"
		out.RawString(prefix)
		out.String(string(in.AssetOut))
	}
	if in.MinAmountOut != nil {
		const prefix string = ",\"min_amount_out\":"
		out.RawString(prefix)
		out.String(string(*in.MinAmountOut))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	if in.Beneficiary != nil {
		const prefix string = ",\"beneficiary\":"
		out.RawString(prefix)
		out.String(string(*in.Beneficiary))
	}
	if in.RefBps != nil {
		const prefix string = ",\"ref_bps\":"
		out.RawString(prefix)
		out.Uint64(uint64(*in.RefBps))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SwapParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp2(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SwapParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp2(l, v)
}
func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp3(in *jlexer.Lexer, out *SchemaReturn) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "supported_chains":
			if in.IsNull() {
				in.Skip()
				out.SupportedChains = nil
			} else {
				in.Delim('[')
				if out.SupportedChains == nil {
					if !in.IsDelim(']') {
						out.SupportedChains = make([]string, 0, 4)
					} else {
						out.SupportedChains = []string{}
					}
				} else {
					out.SupportedChains = (out.SupportedChains)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.SupportedChains = append(out.SupportedChains, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "return_address_chains":
			if in.IsNull() {
				in.Skip()
				out.ReturnAddressChains = nil
			} else {
				in.Delim('[')
				if out.ReturnAddressChains == nil {
					if !in.IsDelim(']') {
						out.ReturnAddressChains = make([]string, 0, 4)
					} else {
						out.ReturnAddressChains = []string{}
					}
				} else {
					out.ReturnAddressChains = (out.ReturnAddressChains)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					v2 = string(in.String())
					out.ReturnAddressChains = append(out.ReturnAddressChains, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "note":
			out.Note = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp3(out *jwriter.Writer, in SchemaReturn) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"supported_chains\":"
		out.RawString(prefix[1:])
		if in.SupportedChains == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.SupportedChains {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.String(string(v4))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"return_address_chains\":"
		out.RawString(prefix)
		if in.ReturnAddressChains == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.ReturnAddressChains {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"note\":"
		out.RawString(prefix)
		out.String(string(in.Note))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SchemaReturn) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp3(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SchemaReturn) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp3(l, v)
}
func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp4(in *jlexer.Lexer, out *ReturnRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "chain":
			out.Chain = string(in.String())
		case "address":
			out.Address = string(in.String())
		case "asset":
			out.Asset = string(in.String())
		case "amount":
			out.Amount = string(in.String())
		case "log":
			(out.Log).UnmarshalTinyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp4(out *jwriter.Writer, in ReturnRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chain\":"
		out.RawString(prefix[1:])
		out.String(string(in.Chain))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"asset\":"
		out.RawString(prefix)
		out.String(string(in.Asset))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"log\":"
		out.RawString(prefix)
		(in.Log).MarshalTinyJSON(out)
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v ReturnRequest) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp4(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *ReturnRequest) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp4(l, v)
}
func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp5(in *jlexer.Lexer, out *ReturnAddress) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "chain":
			out.Chain = string(in.String())
		case "address":
			out.Address = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp5(out *jwriter.Writer, in ReturnAddress) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chain\":"
		out.RawString(prefix[1:])
		out.String(string(in.Chain))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v ReturnAddress) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp5(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *ReturnAddress) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp5(l, v)
}
func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp6(in *jlexer.Lexer, out *RemoveLiquidityParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "lp_amount":
			out.LpAmount = string(in.String())
		case "recipient":
			out.Recipient = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp6(out *jwriter.Writer, in RemoveLiquidityParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"lp_amount\":"
		out.RawString(prefix[1:])
		out.String(string(in.LpAmount))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v RemoveLiquidityParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp6(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *RemoveLiquidityParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp6(l, v)
}
func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp7(in *jlexer.Lexer, out *RegisterTokenParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "mapping_contract":
			out.MappingContract = string(in.String())
		case "chain":
			out.Chain = string(in.String())
		case "description":
			out.Description = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp7(out *jwriter.Writer, in RegisterTokenParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	if in.MappingContract != "" {
		const prefix string = ",\"mapping_contract\":"
		out.RawString(prefix)
		out.String(string(in.MappingContract))
	}
	{
		const prefix string = ",\"chain\":"
		out.RawString(prefix)
		out.String(string(in.Chain))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v RegisterTokenParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp7(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *RegisterTokenParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp7(l, v)
}
func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp8(in *jlexer.Lexer, out *RegisterPoolParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		case "dex_contract_id":
			out.DexContractId = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp8(out *jwriter.Writer, in RegisterPoolParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset0))
	}
	{
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	{
		const prefix string = ",\"dex_contract_id\":"
		out.RawString(prefix)
		out.String(string(in.DexContractId))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v RegisterPoolParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp8(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *RegisterPoolParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp8(l, v)
}
func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp9(in *jlexer.Lexer, out *PoolInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		case "reserve0":
			out.Reserve0 = string(in.String())
		case "reserve1":
			out.Reserve1 = string(in.String())
		case "fee":
			out.Fee = uint64(in.Uint64())
		case "total_lp":
			out.TotalLp = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp9(out *jwriter.Writer, in PoolInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset0))
	}
	{
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	{
		const prefix string = ",\"reserve0\":"
		out.RawString(prefix)
		out.String(string(in.Reserve0))
	}
	{
		const prefix string = ",\"reserve1\":"
		out.RawString(prefix)
		out.String(string(in.Reserve1))
	}
	{
		const prefix string = ",\"fee\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Fee))
	}
	{
		const prefix string = ",\"total_lp\":"
		out.RawString(prefix)
		out.String(string(in.TotalLp))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v PoolInfo) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp9(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *PoolInfo) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp9(l, v)
}
func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp10(in *jlexer.Lexer, out *KeyMap) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		*out = make(KeyMap)
		for !in.IsDelim('}') {
			key := string(in.String())
			in.WantColon()
			var v7 string
			v7 = string(in.String())
			(*out)[key] = v7
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp10(out *jwriter.Writer, in KeyMap) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v8First := true
		for v8Name, v8Value := range in {
			if v8First {
				v8First = false
			} else {
				out.RawByte(',')
			}
			out.String(string(v8Name))
			out.RawByte(':')
			out.String(string(v8Value))
		}
		out.RawByte('}')
	}
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v KeyMap) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp10(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *KeyMap) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp10(l, v)
}
func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp11(in *jlexer.Lexer, out *KeyList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "keys":
			if in.IsNull() {
				in.Skip()
				out.Keys = nil
			} else {
				in.Delim('[')
				if out.Keys == nil {
					if !in.IsDelim(']') {
						out.Keys = make([]string, 0, 4)
					} else {
						out.Keys = []string{}
					}
				} else {
					out.Keys = (out.Keys)[:0]
				}
				for !in.IsDelim(']') {
					var v9 string
					v9 = string(in.String())
					out.Keys = append(out.Keys, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp11(out *jwriter.Writer, in KeyList) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"keys\":"
		out.RawString(prefix[1:])
		if in.Keys == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.Keys {
				if v10 > 0 {
					out.RawByte(',')
				}
				out.String(string(v11))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v KeyList) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp11(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *KeyList) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp11(l, v)
}
func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp12(in *jlexer.Lexer, out *GetPoolParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp12(out *jwriter.Writer, in GetPoolParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset0))
	}
	{
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v GetPoolParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp12(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *GetPoolParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp12(l, v)
}
func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp13(in *jlexer.Lexer, out *FailureLog) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "reason":
			out.Reason = string(in.String())
		case "failed_at_hop":
			out.FailedAtHop = int(in.Int())
		case "original_asset":
			out.OriginalAsset = string(in.String())
		case "original_amount":
			out.OriginalAmount = string(in.String())
		case "intermediate_asset":
			out.IntermediateAsset = string(in.String())
		case "intermediate_amount":
			out.IntermediateAmount = string(in.String())
		case "return_address":
			if in.IsNull() {
				in.Skip()
				out.ReturnAddress = nil
			} else {
				if out.ReturnAddress == nil {
					out.ReturnAddress = new(ReturnAddress)
				}
				(*out.ReturnAddress).UnmarshalTinyJSON(in)
			}
		case "timestamp":
			out.Timestamp = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp13(out *jwriter.Writer, in FailureLog) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix[1:])
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"failed_at_hop\":"
		out.RawString(prefix)
		out.Int(int(in.FailedAtHop))
	}
	{
		const prefix string = ",\"original_asset\":"
		out.RawString(prefix)
		out.String(string(in.OriginalAsset))
	}
	{
		const prefix string = ",\"original_amount\":"
		out.RawString(prefix)
		out.String(string(in.OriginalAmount))
	}
	if in.IntermediateAsset != "" {
		const prefix string = ",\"intermediate_asset\":"
		out.RawString(prefix)
		out.String(string(in.IntermediateAsset))
	}
	if in.IntermediateAmount != "" {
		const prefix string = ",\"intermediate_amount\":"
		out.RawString(prefix)
		out.String(string(in.IntermediateAmount))
	}
	if in.ReturnAddress != nil {
		const prefix string = ",\"return_address\":"
		out.RawString(prefix)
		(*in.ReturnAddress).MarshalTinyJSON(out)
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.String(string(in.Timestamp))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v FailureLog) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp13(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *FailureLog) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp13(l, v)
}
func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp14(in *jlexer.Lexer, out *DexInstruction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "version":
			out.Version = string(in.String())
		case "asset_in":
			out.AssetIn = string(in.String())
		case "asset_out":
			out.AssetOut = string(in.String())
		case "recipient":
			out.Recipient = string(in.String())
		case "min_amount_out":
			if in.IsNull() {
				in.Skip()
				out.MinAmountOut = nil
			} else {
				if out.MinAmountOut == nil {
					out.MinAmountOut = new(string)
				}
				*out.MinAmountOut = string(in.String())
			}
		case "beneficiary":
			if in.IsNull() {
				in.Skip()
				out.Beneficiary = nil
			} else {
				if out.Beneficiary == nil {
					out.Beneficiary = new(string)
				}
				*out.Beneficiary = string(in.String())
			}
		case "ref_bps":
			if in.IsNull() {
				in.Skip()
				out.RefBps = nil
			} else {
				if out.RefBps == nil {
					out.RefBps = new(uint64)
				}
				*out.RefBps = uint64(in.Uint64())
			}
		case "return_address":
			if in.IsNull() {
				in.Skip()
				out.ReturnAddress = nil
			} else {
				if out.ReturnAddress == nil {
					out.ReturnAddress = new(ReturnAddress)
				}
				(*out.ReturnAddress).UnmarshalTinyJSON(in)
			}
		case "metadata":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Metadata = make(map[string]string)
				} else {
					out.Metadata = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v12 string
					v12 = string(in.String())
					(out.Metadata)[key] = v12
					in.WantComma()
				}
				in.Delim('}')
			}
		case "amount_in":
			out.AmountIn = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp14(out *jwriter.Writer, in DexInstruction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	{
		const prefix string = ",\"asset_in\":"
		out.RawString(prefix)
		out.String(string(in.AssetIn))
	}
	{
		const prefix string = ",\"asset_out\":"
		out.RawString(prefix)
		out.String(string(in.AssetOut))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	if in.MinAmountOut != nil {
		const prefix string = ",\"min_amount_out\":"
		out.RawString(prefix)
		out.String(string(*in.MinAmountOut))
	}
	if in.Beneficiary != nil {
		const prefix string = ",\"beneficiary\":"
		out.RawString(prefix)
		out.String(string(*in.Beneficiary))
	}
	if in.RefBps != nil {
		const prefix string = ",\"ref_bps\":"
		out.RawString(prefix)
		out.Uint64(uint64(*in.RefBps))
	}
	if in.ReturnAddress != nil {
		const prefix string = ",\"return_address\":"
		out.RawString(prefix)
		(*in.ReturnAddress).MarshalTinyJSON(out)
	}
	if len(in.Metadata) != 0 {
		const prefix string = ",\"metadata\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v13First := true
			for v13Name, v13Value := range in.Metadata {
				if v13First {
					v13First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v13Name))
				out.RawByte(':')
				out.String(string(v13Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"amount_in\":"
		out.RawString(prefix)
		out.String(string(in.AmountIn))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v DexInstruction) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp14(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *DexInstruction) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp14(l, v)
}
func tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp15(in *jlexer.Lexer, out *AddLiquidityParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount0":
			out.Amount0 = string(in.String())
		case "amount1":
			out.Amount1 = string(in.String())
		case "recipient":
			out.Recipient = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp15(out *jwriter.Writer, in AddLiquidityParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Amount0))
	}
	{
		const prefix string = ",\"amount1\":"
		out.RawString(prefix)
		out.String(string(in.Amount1))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v AddLiquidityParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson73e1cf70EncodeDexRouterV2RouterInternalTinyjsonTmp15(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *AddLiquidityParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson73e1cf70DecodeDexRouterV2RouterInternalTinyjsonTmp15(l, v)
}
