// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package dexinternal

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp(in *jlexer.Lexer, out *TokenInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "mapping_contract":
			out.MappingContract = string(in.String())
		case "string":
			out.Chain = string(in.String())
		case "description":
			out.Description = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp(out *jwriter.Writer, in TokenInfo) {
	out.RawByte('{')
	first := true
	_ = first
	if in.MappingContract != "" {
		const prefix string = ",\"mapping_contract\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.MappingContract))
	}
	{
		const prefix string = ",\"string\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Chain))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v TokenInfo) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *TokenInfo) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp(l, v)
}
func tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp1(in *jlexer.Lexer, out *SwapResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount_out":
			out.AmountOut = string(in.String())
		case "pool_state":
			(out.PoolState).UnmarshalTinyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp1(out *jwriter.Writer, in SwapResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount_out\":"
		out.RawString(prefix[1:])
		out.String(string(in.AmountOut))
	}
	{
		const prefix string = ",\"pool_state\":"
		out.RawString(prefix)
		(in.PoolState).MarshalTinyJSON(out)
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SwapResult) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp1(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SwapResult) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp1(l, v)
}
func tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp2(in *jlexer.Lexer, out *SwapParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset_in":
			out.AssetIn = string(in.String())
		case "amount_in":
			out.AmountIn = string(in.String())
		case "asset_out":
			out.AssetOut = string(in.String())
		case "min_amount_out":
			if in.IsNull() {
				in.Skip()
				out.MinAmountOut = nil
			} else {
				if out.MinAmountOut == nil {
					out.MinAmountOut = new(string)
				}
				*out.MinAmountOut = string(in.String())
			}
		case "recipient":
			out.Recipient = string(in.String())
		case "beneficiary":
			if in.IsNull() {
				in.Skip()
				out.Beneficiary = nil
			} else {
				if out.Beneficiary == nil {
					out.Beneficiary = new(string)
				}
				*out.Beneficiary = string(in.String())
			}
		case "ref_bps":
			if in.IsNull() {
				in.Skip()
				out.RefBps = nil
			} else {
				if out.RefBps == nil {
					out.RefBps = new(uint64)
				}
				*out.RefBps = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp2(out *jwriter.Writer, in SwapParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset_in\":"
		out.RawString(prefix[1:])
		out.String(string(in.AssetIn))
	}
	{
		const prefix string = ",\"amount_in\":"
		out.RawString(prefix)
		out.String(string(in.AmountIn))
	}
	{
		const prefix string = ",\"asset_out\":"
		out.RawString(prefix)
		out.String(string(in.AssetOut))
	}
	if in.MinAmountOut != nil {
		const prefix string = ",\"min_amount_out\":"
		out.RawString(prefix)
		out.String(string(*in.MinAmountOut))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	if in.Beneficiary != nil {
		const prefix string = ",\"beneficiary\":"
		out.RawString(prefix)
		out.String(string(*in.Beneficiary))
	}
	if in.RefBps != nil {
		const prefix string = ",\"ref_bps\":"
		out.RawString(prefix)
		out.Uint64(uint64(*in.RefBps))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SwapParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp2(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SwapParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp2(l, v)
}
func tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp3(in *jlexer.Lexer, out *RemoveLiquidityParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "lp_amount":
			out.LpAmount = string(in.String())
		case "recipient":
			out.Recipient = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp3(out *jwriter.Writer, in RemoveLiquidityParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"lp_amount\":"
		out.RawString(prefix[1:])
		out.String(string(in.LpAmount))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v RemoveLiquidityParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp3(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *RemoveLiquidityParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp3(l, v)
}
func tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp4(in *jlexer.Lexer, out *PoolInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		case "reserve0":
			out.Reserve0 = string(in.String())
		case "reserve1":
			out.Reserve1 = string(in.String())
		case "fee":
			out.Fee = uint64(in.Uint64())
		case "total_lp":
			out.TotalLp = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp4(out *jwriter.Writer, in PoolInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset0))
	}
	{
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	{
		const prefix string = ",\"reserve0\":"
		out.RawString(prefix)
		out.String(string(in.Reserve0))
	}
	{
		const prefix string = ",\"reserve1\":"
		out.RawString(prefix)
		out.String(string(in.Reserve1))
	}
	{
		const prefix string = ",\"fee\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Fee))
	}
	{
		const prefix string = ",\"total_lp\":"
		out.RawString(prefix)
		out.String(string(in.TotalLp))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v PoolInfo) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp4(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *PoolInfo) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp4(l, v)
}
func tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp5(in *jlexer.Lexer, out *MappingContractInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount":
			out.Amount = string(in.String())
		case "to":
			out.To = string(in.String())
		case "from":
			out.From = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp5(out *jwriter.Writer, in MappingContractInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	if in.From != "" {
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.String(string(in.From))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v MappingContractInput) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp5(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *MappingContractInput) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp5(l, v)
}
func tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp6(in *jlexer.Lexer, out *MappedAsset) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset":
			out.Asset = string(in.String())
		case "mapping_contract_id":
			out.MappingContractId = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp6(out *jwriter.Writer, in MappedAsset) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset))
	}
	{
		const prefix string = ",\"mapping_contract_id\":"
		out.RawString(prefix)
		out.String(string(in.MappingContractId))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v MappedAsset) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp6(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *MappedAsset) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp6(l, v)
}
func tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp7(in *jlexer.Lexer, out *InitParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		case "fee_bps":
			out.FeeBps = uint64(in.Uint64())
		case "asset0_mapping_contract":
			out.Asset0MappingContract = string(in.String())
		case "asset1_mapping_contract":
			out.Asset1MappingContract = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp7(out *jwriter.Writer, in InitParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset0))
	}
	{
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	{
		const prefix string = ",\"fee_bps\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.FeeBps))
	}
	if in.Asset0MappingContract != "" {
		const prefix string = ",\"asset0_mapping_contract\":"
		out.RawString(prefix)
		out.String(string(in.Asset0MappingContract))
	}
	if in.Asset1MappingContract != "" {
		const prefix string = ",\"asset1_mapping_contract\":"
		out.RawString(prefix)
		out.String(string(in.Asset1MappingContract))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v InitParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp7(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *InitParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp7(l, v)
}
func tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp8(in *jlexer.Lexer, out *HiveAsset) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset":
			out.Asset = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp8(out *jwriter.Writer, in HiveAsset) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v HiveAsset) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp8(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *HiveAsset) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp8(l, v)
}
func tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp9(in *jlexer.Lexer, out *AddLiquidityParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount0":
			out.Amount0 = string(in.String())
		case "amount1":
			out.Amount1 = string(in.String())
		case "recipient":
			out.Recipient = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp9(out *jwriter.Writer, in AddLiquidityParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Amount0))
	}
	{
		const prefix string = ",\"amount1\":"
		out.RawString(prefix)
		out.String(string(in.Amount1))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v AddLiquidityParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonBbf8afaeEncodeDexDexInternalTinyjsonTmp9(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *AddLiquidityParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonBbf8afaeDecodeDexDexInternalTinyjsonTmp9(l, v)
}
