// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package main

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjson2ff7060fDecodeDexTinyjsonTmp(in *jlexer.Lexer, out *SwapResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount_out":
			out.AmountOut = uint64(in.Uint64())
		case "pool_state":
			(out.PoolState).UnmarshalTinyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexTinyjsonTmp(out *jwriter.Writer, in SwapResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount_out\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.AmountOut))
	}
	{
		const prefix string = ",\"pool_state\":"
		out.RawString(prefix)
		(in.PoolState).MarshalTinyJSON(out)
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SwapResult) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexTinyjsonTmp(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SwapResult) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexTinyjsonTmp(l, v)
}
func tinyjson2ff7060fDecodeDexTinyjsonTmp1(in *jlexer.Lexer, out *SwapParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset_in":
			out.AssetIn = string(in.String())
		case "amount_in":
			out.AmountIn = int64(in.Int64())
		case "asset_out":
			out.AssetOut = string(in.String())
		case "min_amount_out":
			if in.IsNull() {
				in.Skip()
				out.MinAmountOut = nil
			} else {
				if out.MinAmountOut == nil {
					out.MinAmountOut = new(int64)
				}
				*out.MinAmountOut = int64(in.Int64())
			}
		case "recipient":
			out.Recipient = string(in.String())
		case "beneficiary":
			if in.IsNull() {
				in.Skip()
				out.Beneficiary = nil
			} else {
				if out.Beneficiary == nil {
					out.Beneficiary = new(string)
				}
				*out.Beneficiary = string(in.String())
			}
		case "ref_bps":
			if in.IsNull() {
				in.Skip()
				out.RefBps = nil
			} else {
				if out.RefBps == nil {
					out.RefBps = new(int)
				}
				*out.RefBps = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexTinyjsonTmp1(out *jwriter.Writer, in SwapParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset_in\":"
		out.RawString(prefix[1:])
		out.String(string(in.AssetIn))
	}
	{
		const prefix string = ",\"amount_in\":"
		out.RawString(prefix)
		out.Int64(int64(in.AmountIn))
	}
	{
		const prefix string = ",\"asset_out\":"
		out.RawString(prefix)
		out.String(string(in.AssetOut))
	}
	if in.MinAmountOut != nil {
		const prefix string = ",\"min_amount_out\":"
		out.RawString(prefix)
		out.Int64(int64(*in.MinAmountOut))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	if in.Beneficiary != nil {
		const prefix string = ",\"beneficiary\":"
		out.RawString(prefix)
		out.String(string(*in.Beneficiary))
	}
	if in.RefBps != nil {
		const prefix string = ",\"ref_bps\":"
		out.RawString(prefix)
		out.Int(int(*in.RefBps))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SwapParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexTinyjsonTmp1(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SwapParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexTinyjsonTmp1(l, v)
}
func tinyjson2ff7060fDecodeDexTinyjsonTmp2(in *jlexer.Lexer, out *RemoveLiquidityParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "lp_amount":
			out.LpAmount = uint64(in.Uint64())
		case "recipient":
			out.Recipient = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexTinyjsonTmp2(out *jwriter.Writer, in RemoveLiquidityParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"lp_amount\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.LpAmount))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v RemoveLiquidityParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexTinyjsonTmp2(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *RemoveLiquidityParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexTinyjsonTmp2(l, v)
}
func tinyjson2ff7060fDecodeDexTinyjsonTmp3(in *jlexer.Lexer, out *PoolInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		case "reserve0":
			out.Reserve0 = uint64(in.Uint64())
		case "reserve1":
			out.Reserve1 = uint64(in.Uint64())
		case "fee":
			out.Fee = uint64(in.Uint64())
		case "total_lp":
			out.TotalLp = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexTinyjsonTmp3(out *jwriter.Writer, in PoolInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset0))
	}
	{
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	{
		const prefix string = ",\"reserve0\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Reserve0))
	}
	{
		const prefix string = ",\"reserve1\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Reserve1))
	}
	{
		const prefix string = ",\"fee\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Fee))
	}
	{
		const prefix string = ",\"total_lp\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.TotalLp))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v PoolInfo) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexTinyjsonTmp3(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *PoolInfo) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexTinyjsonTmp3(l, v)
}
func tinyjson2ff7060fDecodeDexTinyjsonTmp4(in *jlexer.Lexer, out *InitParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		case "fee_bps":
			out.FeeBps = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexTinyjsonTmp4(out *jwriter.Writer, in InitParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset0))
	}
	{
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	{
		const prefix string = ",\"fee_bps\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.FeeBps))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v InitParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexTinyjsonTmp4(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *InitParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexTinyjsonTmp4(l, v)
}
func tinyjson2ff7060fDecodeDexTinyjsonTmp5(in *jlexer.Lexer, out *AddLiquidityParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount0":
			out.Amount0 = uint64(in.Uint64())
		case "amount1":
			out.Amount1 = uint64(in.Uint64())
		case "recipient":
			out.Recipient = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2ff7060fEncodeDexTinyjsonTmp5(out *jwriter.Writer, in AddLiquidityParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount0\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.Amount0))
	}
	{
		const prefix string = ",\"amount1\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Amount1))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v AddLiquidityParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2ff7060fEncodeDexTinyjsonTmp5(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *AddLiquidityParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2ff7060fDecodeDexTinyjsonTmp5(l, v)
}
