// TEMPORARY AUTOGENERATED FILE: tinyjson stub code to make the package
// compilable during generation.

package  main

import (
  "github.com/CosmWasm/tinyjson/jwriter"
  "github.com/CosmWasm/tinyjson/jlexer"
)

func ( AddLiquidityParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AddLiquidityParams ) UnmarshalJSON([]byte) error { return nil }
func ( AddLiquidityParams ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* AddLiquidityParams ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_AddLiquidityParams *AddLiquidityParams

func ( InitParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* InitParams ) UnmarshalJSON([]byte) error { return nil }
func ( InitParams ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* InitParams ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_InitParams *InitParams

func ( PoolInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PoolInfo ) UnmarshalJSON([]byte) error { return nil }
func ( PoolInfo ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* PoolInfo ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_PoolInfo *PoolInfo

func ( RemoveLiquidityParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RemoveLiquidityParams ) UnmarshalJSON([]byte) error { return nil }
func ( RemoveLiquidityParams ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* RemoveLiquidityParams ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_RemoveLiquidityParams *RemoveLiquidityParams

func ( SwapParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SwapParams ) UnmarshalJSON([]byte) error { return nil }
func ( SwapParams ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* SwapParams ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_SwapParams *SwapParams
