// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package asset

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjsonEf77c78aDecodeGithubComVscEcoDexContractsContractsDexAssetTinyjsonTmp(in *jlexer.Lexer, out *MappedAsset) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset":
			out.Asset = string(in.String())
		case "mapping_contract_id":
			out.MappingContractId = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonEf77c78aEncodeGithubComVscEcoDexContractsContractsDexAssetTinyjsonTmp(out *jwriter.Writer, in MappedAsset) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset))
	}
	{
		const prefix string = ",\"mapping_contract_id\":"
		out.RawString(prefix)
		out.String(string(in.MappingContractId))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v MappedAsset) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonEf77c78aEncodeGithubComVscEcoDexContractsContractsDexAssetTinyjsonTmp(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *MappedAsset) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonEf77c78aDecodeGithubComVscEcoDexContractsContractsDexAssetTinyjsonTmp(l, v)
}
func tinyjsonEf77c78aDecodeGithubComVscEcoDexContractsContractsDexAssetTinyjsonTmp1(in *jlexer.Lexer, out *HiveAsset) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset":
			out.Asset = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonEf77c78aEncodeGithubComVscEcoDexContractsContractsDexAssetTinyjsonTmp1(out *jwriter.Writer, in HiveAsset) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v HiveAsset) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonEf77c78aEncodeGithubComVscEcoDexContractsContractsDexAssetTinyjsonTmp1(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *HiveAsset) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonEf77c78aDecodeGithubComVscEcoDexContractsContractsDexAssetTinyjsonTmp1(l, v)
}
