// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp(in *jlexer.Lexer, out *UnmapParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount":
			out.Amount = string(in.String())
		case "to":
			out.To = string(in.String())
		case "from":
			out.From = string(in.String())
		case "deduct_fee":
			out.DeductFee = bool(in.Bool())
		case "max_fee":
			if in.IsNull() {
				in.Skip()
				out.MaxFee = nil
			} else {
				if out.MaxFee == nil {
					out.MaxFee = new(int64)
				}
				*out.MaxFee = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp(out *jwriter.Writer, in UnmapParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	if in.From != "" {
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.String(string(in.From))
	}
	if in.DeductFee {
		const prefix string = ",\"deduct_fee\":"
		out.RawString(prefix)
		out.Bool(bool(in.DeductFee))
	}
	if in.MaxFee != nil {
		const prefix string = ",\"max_fee\":"
		out.RawString(prefix)
		out.Int64(int64(*in.MaxFee))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v UnmapParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *UnmapParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp1(in *jlexer.Lexer, out *TokenInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "mapping_contract":
			out.MappingContract = string(in.String())
		case "chain":
			out.Chain = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "decimals":
			out.Decimals = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp1(out *jwriter.Writer, in TokenInfo) {
	out.RawByte('{')
	first := true
	_ = first
	if in.MappingContract != "" {
		const prefix string = ",\"mapping_contract\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.MappingContract))
	}
	{
		const prefix string = ",\"chain\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Chain))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.Int(int(in.Decimals))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v TokenInfo) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp1(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *TokenInfo) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp1(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp2(in *jlexer.Lexer, out *SwapResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount_out":
			out.AmountOut = string(in.String())
		case "pool_state":
			(out.PoolState).UnmarshalTinyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp2(out *jwriter.Writer, in SwapResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount_out\":"
		out.RawString(prefix[1:])
		out.String(string(in.AmountOut))
	}
	{
		const prefix string = ",\"pool_state\":"
		out.RawString(prefix)
		(in.PoolState).MarshalTinyJSON(out)
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SwapResult) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp2(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SwapResult) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp2(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp3(in *jlexer.Lexer, out *SwapParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset_in":
			out.AssetIn = string(in.String())
		case "amount_in":
			out.AmountIn = string(in.String())
		case "asset_out":
			out.AssetOut = string(in.String())
		case "min_amount_out":
			if in.IsNull() {
				in.Skip()
				out.MinAmountOut = nil
			} else {
				if out.MinAmountOut == nil {
					out.MinAmountOut = new(string)
				}
				*out.MinAmountOut = string(in.String())
			}
		case "from":
			out.From = string(in.String())
		case "to":
			out.To = string(in.String())
		case "beneficiary":
			if in.IsNull() {
				in.Skip()
				out.Beneficiary = nil
			} else {
				if out.Beneficiary == nil {
					out.Beneficiary = new(string)
				}
				*out.Beneficiary = string(in.String())
			}
		case "ref_bps":
			if in.IsNull() {
				in.Skip()
				out.RefBps = nil
			} else {
				if out.RefBps == nil {
					out.RefBps = new(uint64)
				}
				*out.RefBps = uint64(in.Uint64())
			}
		case "pre_deposited":
			out.PreDeposited = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp3(out *jwriter.Writer, in SwapParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset_in\":"
		out.RawString(prefix[1:])
		out.String(string(in.AssetIn))
	}
	{
		const prefix string = ",\"amount_in\":"
		out.RawString(prefix)
		out.String(string(in.AmountIn))
	}
	{
		const prefix string = ",\"asset_out\":"
		out.RawString(prefix)
		out.String(string(in.AssetOut))
	}
	if in.MinAmountOut != nil {
		const prefix string = ",\"min_amount_out\":"
		out.RawString(prefix)
		out.String(string(*in.MinAmountOut))
	}
	if in.From != "" {
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.String(string(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	if in.Beneficiary != nil {
		const prefix string = ",\"beneficiary\":"
		out.RawString(prefix)
		out.String(string(*in.Beneficiary))
	}
	if in.RefBps != nil {
		const prefix string = ",\"ref_bps\":"
		out.RawString(prefix)
		out.Uint64(uint64(*in.RefBps))
	}
	if in.PreDeposited {
		const prefix string = ",\"pre_deposited\":"
		out.RawString(prefix)
		out.Bool(bool(in.PreDeposited))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SwapParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp3(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SwapParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp3(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp4(in *jlexer.Lexer, out *SchemaReturn) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "supported_chains":
			if in.IsNull() {
				in.Skip()
				out.SupportedChains = nil
			} else {
				in.Delim('[')
				if out.SupportedChains == nil {
					if !in.IsDelim(']') {
						out.SupportedChains = make([]string, 0, 4)
					} else {
						out.SupportedChains = []string{}
					}
				} else {
					out.SupportedChains = (out.SupportedChains)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.SupportedChains = append(out.SupportedChains, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "return_address_chains":
			if in.IsNull() {
				in.Skip()
				out.ReturnAddressChains = nil
			} else {
				in.Delim('[')
				if out.ReturnAddressChains == nil {
					if !in.IsDelim(']') {
						out.ReturnAddressChains = make([]string, 0, 4)
					} else {
						out.ReturnAddressChains = []string{}
					}
				} else {
					out.ReturnAddressChains = (out.ReturnAddressChains)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					v2 = string(in.String())
					out.ReturnAddressChains = append(out.ReturnAddressChains, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "tokens":
			if in.IsNull() {
				in.Skip()
				out.Tokens = nil
			} else {
				in.Delim('[')
				if out.Tokens == nil {
					if !in.IsDelim(']') {
						out.Tokens = make([]RegisterTokenParams, 0, 0)
					} else {
						out.Tokens = []RegisterTokenParams{}
					}
				} else {
					out.Tokens = (out.Tokens)[:0]
				}
				for !in.IsDelim(']') {
					var v3 RegisterTokenParams
					(v3).UnmarshalTinyJSON(in)
					out.Tokens = append(out.Tokens, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "note":
			out.Note = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp4(out *jwriter.Writer, in SchemaReturn) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"supported_chains\":"
		out.RawString(prefix[1:])
		if in.SupportedChains == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v4, v5 := range in.SupportedChains {
				if v4 > 0 {
					out.RawByte(',')
				}
				out.String(string(v5))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"return_address_chains\":"
		out.RawString(prefix)
		if in.ReturnAddressChains == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v6, v7 := range in.ReturnAddressChains {
				if v6 > 0 {
					out.RawByte(',')
				}
				out.String(string(v7))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"tokens\":"
		out.RawString(prefix)
		if in.Tokens == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Tokens {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalTinyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"note\":"
		out.RawString(prefix)
		out.String(string(in.Note))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SchemaReturn) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp4(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SchemaReturn) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp4(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp5(in *jlexer.Lexer, out *ReturnAddress) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "chain":
			out.Chain = string(in.String())
		case "address":
			out.Address = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp5(out *jwriter.Writer, in ReturnAddress) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chain\":"
		out.RawString(prefix[1:])
		out.String(string(in.Chain))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v ReturnAddress) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp5(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *ReturnAddress) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp5(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp6(in *jlexer.Lexer, out *RemoveLiquidityParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "lp_amount":
			out.LpAmount = string(in.String())
		case "recipient":
			out.Recipient = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp6(out *jwriter.Writer, in RemoveLiquidityParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"lp_amount\":"
		out.RawString(prefix[1:])
		out.String(string(in.LpAmount))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v RemoveLiquidityParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp6(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *RemoveLiquidityParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp6(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp7(in *jlexer.Lexer, out *RegisterTokenParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "mapping_contract":
			out.MappingContract = string(in.String())
		case "chain":
			out.Chain = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "decimals":
			out.Decimals = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp7(out *jwriter.Writer, in RegisterTokenParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	if in.MappingContract != "" {
		const prefix string = ",\"mapping_contract\":"
		out.RawString(prefix)
		out.String(string(in.MappingContract))
	}
	{
		const prefix string = ",\"chain\":"
		out.RawString(prefix)
		out.String(string(in.Chain))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.Int(int(in.Decimals))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v RegisterTokenParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp7(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *RegisterTokenParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp7(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp8(in *jlexer.Lexer, out *RegisterPoolParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		case "dex_contract_id":
			out.DexContractId = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp8(out *jwriter.Writer, in RegisterPoolParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset0))
	}
	{
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	{
		const prefix string = ",\"dex_contract_id\":"
		out.RawString(prefix)
		out.String(string(in.DexContractId))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v RegisterPoolParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp8(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *RegisterPoolParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp8(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp9(in *jlexer.Lexer, out *PoolInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		case "reserve0":
			out.Reserve0 = string(in.String())
		case "reserve1":
			out.Reserve1 = string(in.String())
		case "fee":
			out.Fee = uint64(in.Uint64())
		case "total_lp":
			out.TotalLp = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp9(out *jwriter.Writer, in PoolInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset0))
	}
	{
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	{
		const prefix string = ",\"reserve0\":"
		out.RawString(prefix)
		out.String(string(in.Reserve0))
	}
	{
		const prefix string = ",\"reserve1\":"
		out.RawString(prefix)
		out.String(string(in.Reserve1))
	}
	{
		const prefix string = ",\"fee\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Fee))
	}
	{
		const prefix string = ",\"total_lp\":"
		out.RawString(prefix)
		out.String(string(in.TotalLp))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v PoolInfo) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp9(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *PoolInfo) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp9(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp10(in *jlexer.Lexer, out *MappingContractInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount":
			out.Amount = string(in.String())
		case "to":
			out.To = string(in.String())
		case "from":
			out.From = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp10(out *jwriter.Writer, in MappingContractInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	if in.From != "" {
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.String(string(in.From))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v MappingContractInput) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp10(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *MappingContractInput) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp10(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp11(in *jlexer.Lexer, out *MappingContractInfoReturn) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "symbol":
			out.Symbol = string(in.String())
		case "decimals":
			out.Decimals = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp11(out *jwriter.Writer, in MappingContractInfoReturn) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.String(string(in.Decimals))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v MappingContractInfoReturn) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp11(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *MappingContractInfoReturn) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp11(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp12(in *jlexer.Lexer, out *KeyMap) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		*out = make(KeyMap)
		for !in.IsDelim('}') {
			key := string(in.String())
			in.WantColon()
			var v10 string
			v10 = string(in.String())
			(*out)[key] = v10
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp12(out *jwriter.Writer, in KeyMap) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v11First := true
		for v11Name, v11Value := range in {
			if v11First {
				v11First = false
			} else {
				out.RawByte(',')
			}
			out.String(string(v11Name))
			out.RawByte(':')
			out.String(string(v11Value))
		}
		out.RawByte('}')
	}
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v KeyMap) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp12(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *KeyMap) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp12(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp13(in *jlexer.Lexer, out *KeyList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "keys":
			if in.IsNull() {
				in.Skip()
				out.Keys = nil
			} else {
				in.Delim('[')
				if out.Keys == nil {
					if !in.IsDelim(']') {
						out.Keys = make([]string, 0, 4)
					} else {
						out.Keys = []string{}
					}
				} else {
					out.Keys = (out.Keys)[:0]
				}
				for !in.IsDelim(']') {
					var v12 string
					v12 = string(in.String())
					out.Keys = append(out.Keys, v12)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp13(out *jwriter.Writer, in KeyList) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"keys\":"
		out.RawString(prefix[1:])
		if in.Keys == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v13, v14 := range in.Keys {
				if v13 > 0 {
					out.RawByte(',')
				}
				out.String(string(v14))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v KeyList) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp13(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *KeyList) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp13(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp14(in *jlexer.Lexer, out *InitParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		case "fee_bps":
			out.FeeBps = uint64(in.Uint64())
		case "asset0_mapping_contract":
			out.Asset0MappingContract = string(in.String())
		case "asset1_mapping_contract":
			out.Asset1MappingContract = string(in.String())
		case "router_contract":
			out.RouterContract = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp14(out *jwriter.Writer, in InitParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset0))
	}
	{
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	{
		const prefix string = ",\"fee_bps\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.FeeBps))
	}
	if in.Asset0MappingContract != "" {
		const prefix string = ",\"asset0_mapping_contract\":"
		out.RawString(prefix)
		out.String(string(in.Asset0MappingContract))
	}
	if in.Asset1MappingContract != "" {
		const prefix string = ",\"asset1_mapping_contract\":"
		out.RawString(prefix)
		out.String(string(in.Asset1MappingContract))
	}
	if in.RouterContract != "" {
		const prefix string = ",\"router_contract\":"
		out.RawString(prefix)
		out.String(string(in.RouterContract))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v InitParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp14(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *InitParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp14(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp15(in *jlexer.Lexer, out *GetPoolParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp15(out *jwriter.Writer, in GetPoolParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset0))
	}
	{
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v GetPoolParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp15(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *GetPoolParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp15(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp16(in *jlexer.Lexer, out *DexInstruction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "version":
			out.Version = string(in.String())
		case "asset_in":
			out.AssetIn = string(in.String())
		case "asset_out":
			out.AssetOut = string(in.String())
		case "amount_in":
			out.AmountIn = string(in.String())
		case "min_amount_out":
			if in.IsNull() {
				in.Skip()
				out.MinAmountOut = nil
			} else {
				if out.MinAmountOut == nil {
					out.MinAmountOut = new(string)
				}
				*out.MinAmountOut = string(in.String())
			}
		case "beneficiary":
			if in.IsNull() {
				in.Skip()
				out.Beneficiary = nil
			} else {
				if out.Beneficiary == nil {
					out.Beneficiary = new(string)
				}
				*out.Beneficiary = string(in.String())
			}
		case "ref_bps":
			if in.IsNull() {
				in.Skip()
				out.RefBps = nil
			} else {
				if out.RefBps == nil {
					out.RefBps = new(uint64)
				}
				*out.RefBps = uint64(in.Uint64())
			}
		case "amount0":
			out.Amount0 = string(in.String())
		case "amount1":
			out.Amount1 = string(in.String())
		case "lp_amount":
			out.LpAmount = string(in.String())
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		case "recipient":
			out.Recipient = string(in.String())
		case "return_address":
			if in.IsNull() {
				in.Skip()
				out.ReturnAddress = nil
			} else {
				if out.ReturnAddress == nil {
					out.ReturnAddress = new(ReturnAddress)
				}
				(*out.ReturnAddress).UnmarshalTinyJSON(in)
			}
		case "metadata":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Metadata = make(map[string]string)
				} else {
					out.Metadata = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v15 string
					v15 = string(in.String())
					(out.Metadata)[key] = v15
					in.WantComma()
				}
				in.Delim('}')
			}
		case "destination_chain":
			out.DestinationChain = string(in.String())
		case "max_fee":
			if in.IsNull() {
				in.Skip()
				out.MaxFee = nil
			} else {
				if out.MaxFee == nil {
					out.MaxFee = new(int64)
				}
				*out.MaxFee = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp16(out *jwriter.Writer, in DexInstruction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	if in.AssetIn != "" {
		const prefix string = ",\"asset_in\":"
		out.RawString(prefix)
		out.String(string(in.AssetIn))
	}
	if in.AssetOut != "" {
		const prefix string = ",\"asset_out\":"
		out.RawString(prefix)
		out.String(string(in.AssetOut))
	}
	if in.AmountIn != "" {
		const prefix string = ",\"amount_in\":"
		out.RawString(prefix)
		out.String(string(in.AmountIn))
	}
	if in.MinAmountOut != nil {
		const prefix string = ",\"min_amount_out\":"
		out.RawString(prefix)
		out.String(string(*in.MinAmountOut))
	}
	if in.Beneficiary != nil {
		const prefix string = ",\"beneficiary\":"
		out.RawString(prefix)
		out.String(string(*in.Beneficiary))
	}
	if in.RefBps != nil {
		const prefix string = ",\"ref_bps\":"
		out.RawString(prefix)
		out.Uint64(uint64(*in.RefBps))
	}
	if in.Amount0 != "" {
		const prefix string = ",\"amount0\":"
		out.RawString(prefix)
		out.String(string(in.Amount0))
	}
	if in.Amount1 != "" {
		const prefix string = ",\"amount1\":"
		out.RawString(prefix)
		out.String(string(in.Amount1))
	}
	if in.LpAmount != "" {
		const prefix string = ",\"lp_amount\":"
		out.RawString(prefix)
		out.String(string(in.LpAmount))
	}
	if in.Asset0 != "" {
		const prefix string = ",\"asset0\":"
		out.RawString(prefix)
		out.String(string(in.Asset0))
	}
	if in.Asset1 != "" {
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	if in.ReturnAddress != nil {
		const prefix string = ",\"return_address\":"
		out.RawString(prefix)
		(*in.ReturnAddress).MarshalTinyJSON(out)
	}
	if len(in.Metadata) != 0 {
		const prefix string = ",\"metadata\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v16First := true
			for v16Name, v16Value := range in.Metadata {
				if v16First {
					v16First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v16Name))
				out.RawByte(':')
				out.String(string(v16Value))
			}
			out.RawByte('}')
		}
	}
	if in.DestinationChain != "" {
		const prefix string = ",\"destination_chain\":"
		out.RawString(prefix)
		out.String(string(in.DestinationChain))
	}
	if in.MaxFee != nil {
		const prefix string = ",\"max_fee\":"
		out.RawString(prefix)
		out.Int64(int64(*in.MaxFee))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v DexInstruction) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp16(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *DexInstruction) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp16(l, v)
}
func tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp17(in *jlexer.Lexer, out *AddLiquidityParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount0":
			out.Amount0 = string(in.String())
		case "amount1":
			out.Amount1 = string(in.String())
		case "recipient":
			out.Recipient = string(in.String())
		case "pre_deposited_0":
			out.PreDeposited0 = bool(in.Bool())
		case "pre_deposited_1":
			out.PreDeposited1 = bool(in.Bool())
		case "min_lp_out":
			out.MinLpOut = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp17(out *jwriter.Writer, in AddLiquidityParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Amount0))
	}
	{
		const prefix string = ",\"amount1\":"
		out.RawString(prefix)
		out.String(string(in.Amount1))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	if in.PreDeposited0 {
		const prefix string = ",\"pre_deposited_0\":"
		out.RawString(prefix)
		out.Bool(bool(in.PreDeposited0))
	}
	if in.PreDeposited1 {
		const prefix string = ",\"pre_deposited_1\":"
		out.RawString(prefix)
		out.Bool(bool(in.PreDeposited1))
	}
	if in.MinLpOut != "" {
		const prefix string = ",\"min_lp_out\":"
		out.RawString(prefix)
		out.String(string(in.MinLpOut))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v AddLiquidityParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp17(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *AddLiquidityParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeGithubComVscEcoDexContractsContractsTypesTinyjsonTmp17(l, v)
}
